# Generated by Django 4.2 on 2024-04-02 01:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='banner',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
